//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.AuthorsBooks = new HashSet<AuthorsBooks>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> PublisherId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorsBooks> AuthorsBooks { get; set; }
        public virtual BookDetails BookDetail { get; set; }
        public virtual Publishers Publisher { get; set; }
    }
}
